apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
# namespace: wu
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      #imagePullSecrets:
      #- name: ghcr
      containers:
      - name: nginx
        image: ghcr.io/nginx:stable
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 80
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-abc
# namespace: wu
spec:
  selector:
    app: nginx
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
#   nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: nginx
# namespace: wu
spec:
  ingressClassName: public
  rules:
  - host: abc.deoops.com
    http:
      paths:
      - backend:
          service:
            name: nginx-abc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - abc.deoops.com
    secretName: abc.deoops.com.tls
